spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql