spring:
  main:
    log-startup-info: true # выводим служебную информацию
    banner-mode: off       # не выводим баннерlogging.level:
logging.level:
  ru.yandex.practicum.shareit: TRACE
  org.zalando.logbook: TRACE
