spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: dbuser
    password: 12345
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql
logging.level.org.springframework: INFO