CREATE TABLE if not exists Users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT uniqueEmails UNIQUE(email)
);

CREATE TABLE IF NOT exists Items(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES Users(user_id),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    available boolean
);

CREATE TABLE IF NOT exists Comments(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES Users(user_id),
    item_id BIGINT REFERENCES Items(item_id),
    text VARCHAR(1000) NOT NULL,
    created timestamp WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT exists Bookings(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booker_id BIGINT REFERENCES Users(user_id),
    item_id BIGINT REFERENCES Items(item_id),
    status VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    start timestamp WITHOUT TIME ZONE NOT NULL,
    finish timestamp WITHOUT TIME ZONE NOT NULL
);