CREATE TABLE if NOT EXISTS Users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT uniqueEmails UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS Requests(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES Users(user_id),
    text VARCHAR(1000),
    description VARCHAR(1000),
    created timestamp WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS Items(
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES Users(user_id),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available boolean,
    request_id BIGINT REFERENCES Requests(request_id)
);

CREATE TABLE IF NOT EXISTS Comments(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES Users(user_id),
    item_id BIGINT REFERENCES Items(item_id),
    text VARCHAR(1000) NOT NULL,
    created timestamp WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS Bookings(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booker_id BIGINT REFERENCES Users(user_id),
    item_id BIGINT REFERENCES Items(item_id),
    status VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    start timestamp WITHOUT TIME ZONE NOT NULL,
    finish timestamp WITHOUT TIME ZONE NOT NULL
);